In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [2]:
credit_risk = pd.read_csv(r"C:\Users\SHREYA PAI\Files\credit_risk_dataset.csv")

In [3]:
credit_risk.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4


In [4]:
credit_risk.shape

(32581, 12)

In [5]:
credit_risk.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000


In [6]:
credit_risk_copy = credit_risk.copy()

In [7]:
credit_risk.pivot_table(index='person_age', columns='loan_status', values='person_income', aggfunc='count').reset_index().sort_values(by='person_age', ascending=False)

loan_status,person_age,0,1
57,144,3.0,NaN
56,123,2.0,NaN
55,94,1.0,NaN
54,84,1.0,NaN
53,80,1.0,NaN
52,78,1.0,NaN
51,76,1.0,NaN
50,73,3.0,NaN
49,70,5.0,2.0
48,69,5.0,NaN


In [8]:
cr_age_rmvd = credit_risk[credit_risk['person_age']<=70]
cr_age_rmvd.reset_index(drop=True, inplace=True)

In [9]:
display(cr_age_rmvd.shape)
display(cr_age_rmvd.head())

(32568, 12)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4


In [10]:
cr_age_rmvd.pivot_table(index='person_emp_length', columns='loan_status', values='person_income', aggfunc='count').reset_index().sort_values(by='person_emp_length', ascending=False)

loan_status,person_emp_length,0,1
34,123.0,1.0,1.0
33,38.0,1.0,NaN
32,34.0,NaN,1.0
31,31.0,4.0,NaN
30,30.0,1.0,1.0
29,29.0,NaN,1.0
28,28.0,3.0,NaN
27,27.0,4.0,1.0
26,26.0,5.0,1.0
25,25.0,8.0,NaN


In [11]:
cr_emp_length_rmvd = cr_age_rmvd[cr_age_rmvd['person_emp_length']<=47]
cr_emp_length_rmvd.reset_index(drop=True, inplace=True)

In [12]:
display(cr_emp_length_rmvd.shape)
display(cr_emp_length_rmvd.head())

(31671, 12)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
1,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
2,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
3,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
4,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2


In [13]:
cr_emp_length_rmvd.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,31671.000000,3.167100e+04,31671.000000,31671.000000,28626.000000,31671.000000,31671.000000,31671.000000
mean,27.717754,6.649231e+04,4.780714,9660.637492,11.040070,0.215497,0.169621,5.804395
std,6.159859,5.277413e+04,4.028718,6334.716643,3.229507,0.411173,0.106275,4.048776
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.936600e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.600000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,8.000000e+04,7.000000,12500.000000,13.480000,0.000000,0.230000,8.000000
max,70.000000,2.039784e+06,38.000000,35000.000000,23.220000,1.000000,0.830000,30.000000


In [14]:
cr_emp_length_rmvd.isnull().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length                0
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3045
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [15]:
cr_data = cr_emp_length_rmvd.copy()

In [16]:
cr_data.fillna({'loan_int_rate':cr_data['loan_int_rate'].median()}, inplace=True)

In [17]:
cr_data.isnull().sum()

person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_status                   0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
dtype: int64

In [18]:
cr_data.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,31671.000000,3.167100e+04,31671.000000,31671.000000,31671.000000,31671.000000,31671.000000,31671.000000
mean,27.717754,6.649231e+04,4.780714,9660.637492,11.035256,0.215497,0.169621,5.804395
std,6.159859,5.277413e+04,4.028718,6334.716643,3.070364,0.411173,0.106275,4.048776
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.936600e+04,2.000000,5000.000000,8.490000,0.000000,0.090000,3.000000
50%,26.000000,5.600000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,8.000000e+04,7.000000,12500.000000,13.160000,0.000000,0.230000,8.000000
max,70.000000,2.039784e+06,38.000000,35000.000000,23.220000,1.000000,0.830000,30.000000


In [19]:
cr_data.groupby('loan_status').count()['person_age']

loan_status
0    24846
1     6825
Name: person_age, dtype: int64

In [20]:
cr_data.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
1,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
2,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
3,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
4,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2


In [21]:
cr_data.groupby('person_home_ownership').count()['loan_intent']

person_home_ownership
MORTGAGE    13088
OTHER         107
OWN          2410
RENT        16066
Name: loan_intent, dtype: int64

In [22]:
cr_data.groupby('loan_intent').count()['person_home_ownership']

loan_intent
DEBTCONSOLIDATION    5064
EDUCATION            6288
HOMEIMPROVEMENT      3510
MEDICAL              5891
PERSONAL             5365
VENTURE              5553
Name: person_home_ownership, dtype: int64

In [23]:
cr_data.groupby('loan_grade').count()['person_home_ownership']

loan_grade
A    10365
B    10181
C     6318
D     3555
E      952
F      236
G       64
Name: person_home_ownership, dtype: int64

In [24]:
cr_data_copy = cr_data.drop('loan_grade', axis=1)

In [25]:
display(cr_data_copy.shape)
display(cr_data_copy.head())

(31671, 11)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,21,9600,OWN,5.0,EDUCATION,1000,11.14,0,0.10,N,2
1,25,9600,MORTGAGE,1.0,MEDICAL,5500,12.87,1,0.57,N,3
2,23,65500,RENT,4.0,MEDICAL,35000,15.23,1,0.53,N,2
3,24,54400,RENT,8.0,MEDICAL,35000,14.27,1,0.55,Y,4
4,21,9900,OWN,2.0,VENTURE,2500,7.14,1,0.25,N,2


**Categorical Features Treatment**

In [26]:
cr_data_cat_treated = cr_data_copy.copy()

In [27]:
cr_data_cat_treated.groupby('person_home_ownership').count()['person_age']

person_home_ownership
MORTGAGE    13088
OTHER         107
OWN          2410
RENT        16066
Name: person_age, dtype: int64

In [28]:
person_home_ownership = pd.get_dummies(cr_data_cat_treated['person_home_ownership'], drop_first=True).astype(int)
person_loan_intent = pd.get_dummies(cr_data_cat_treated['loan_intent'], drop_first=True).astype(int)
cr_data_cat_treated['cb_person_default_on_file_binary'] = np.where(cr_data_cat_treated['cb_person_default_on_file']=='Y', 1, 0)
cr_data_cat_treated.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,cb_person_default_on_file_binary
0,21,9600,OWN,5.0,EDUCATION,1000,11.14,0,0.10,N,2,0
1,25,9600,MORTGAGE,1.0,MEDICAL,5500,12.87,1,0.57,N,3,0
2,23,65500,RENT,4.0,MEDICAL,35000,15.23,1,0.53,N,2,0
3,24,54400,RENT,8.0,MEDICAL,35000,14.27,1,0.55,Y,4,1
4,21,9900,OWN,2.0,VENTURE,2500,7.14,1,0.25,N,2,0


In [29]:
display(person_home_ownership)
display(person_loan_intent)

,OTHER,OWN,RENT
0,0,1,0
1,0,0,0
2,0,0,1
3,0,0,1
4,0,1,0
...,...,...,...
31666,0,0,0
31667,0,0,0
31668,0,0,1
31669,0,0,0


,EDUCATION,HOMEIMPROVEMENT,MEDICAL,PERSONAL,VENTURE
0,1,0,0,0,0
1,0,0,1,0,0
2,0,0,1,0,0
3,0,0,1,0,0
4,0,0,0,0,1
...,...,...,...,...,...
31666,0,0,0,1,0
31667,0,0,0,1,0
31668,0,1,0,0,0
31669,0,0,0,1,0


In [30]:
data_to_scale = cr_data_cat_treated.drop(['person_home_ownership', 'loan_intent', 'loan_status', 'cb_person_default_on_file', 'cb_person_default_on_file_binary'], axis=1)

In [31]:
data_to_scale.head()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length
0,21,9600,5.0,1000,11.14,0.10,2
1,25,9600,1.0,5500,12.87,0.57,3
2,23,65500,4.0,35000,15.23,0.53,2
3,24,54400,8.0,35000,14.27,0.55,4
4,21,9900,2.0,2500,7.14,0.25,2


In [32]:
scaler = StandardScaler()

In [33]:
data_to_scale.columns

Index(['person_age', 'person_income', 'person_emp_length', 'loan_amnt',
       'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length'],
      dtype='object')

In [34]:
scaled_data = scaler.fit_transform(data_to_scale)
scaled_data

array([[-1.09058679, -1.07805103,  0.05443152, ...,  0.03411508,
        -0.655113  , -0.93965566],
       [-0.44121099, -1.07805103, -0.93845588, ...,  0.59757502,
         3.76746129, -0.69266353],
       [-0.76589889, -0.01880318, -0.19379033, ...,  1.36622557,
         3.39107199, -0.93965566],
       ...,
       [ 6.05254702,  0.18016109, -0.44201218, ..., -0.01473982,
         2.73239071,  5.48213962],
       [ 4.59145147,  1.58238543,  0.05443152, ...,  0.14485288,
        -0.655113  ,  4.98815537],
       [ 6.21489097, -0.46410415, -0.69023403, ..., -0.34043921,
        -0.18462637,  5.97612388]], shape=(31671, 7))

In [35]:
scaled_df = pd.DataFrame(scaled_data, columns=['person_age', 'person_income', 'person_emp_length', 'loan_amnt','loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length'])
scaled_df.head()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length
0,-1.090587,-1.078051,0.054432,-1.367192,0.034115,-0.655113,-0.939656
1,-0.441211,-1.078051,-0.938456,-0.656810,0.597575,3.767461,-0.692664
2,-0.765899,-0.018803,-0.193790,4.000141,1.366226,3.391072,-0.939656
3,-0.603555,-0.229137,0.799097,4.000141,1.053554,3.579267,-0.445671
4,-1.090587,-1.072366,-0.690234,-1.130398,-1.268682,0.756347,-0.939656


In [36]:
scaled_df.shape

(31671, 7)

In [37]:
scaled_data_combined = pd.concat([scaled_df, person_home_ownership, person_loan_intent], axis=1)
scaled_data_combined['cb_person_default_on_file'] = cr_data_cat_treated['cb_person_default_on_file_binary']
scaled_data_combined['loan_status'] = cr_data_cat_treated['loan_status']
scaled_data_combined.head()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,OTHER,OWN,RENT,EDUCATION,HOMEIMPROVEMENT,MEDICAL,PERSONAL,VENTURE,cb_person_default_on_file,loan_status
0,-1.090587,-1.078051,0.054432,-1.367192,0.034115,-0.655113,-0.939656,0,1,0,1,0,0,0,0,0,0
1,-0.441211,-1.078051,-0.938456,-0.656810,0.597575,3.767461,-0.692664,0,0,0,0,0,1,0,0,0,1
2,-0.765899,-0.018803,-0.193790,4.000141,1.366226,3.391072,-0.939656,0,0,1,0,0,1,0,0,0,1
3,-0.603555,-0.229137,0.799097,4.000141,1.053554,3.579267,-0.445671,0,0,1,0,0,1,0,0,1,1
4,-1.090587,-1.072366,-0.690234,-1.130398,-1.268682,0.756347,-0.939656,0,1,0,0,0,0,0,1,0,1


In [38]:
scaled_data_combined.shape

(31671, 17)

In [39]:
scaled_data_combined.groupby('loan_status').count()['EDUCATION']

loan_status
0    24846
1     6825
Name: EDUCATION, dtype: int64

In [40]:
target = scaled_data_combined['loan_status']
features = scaled_data_combined.drop('loan_status', axis=1)

**Data Balancing & Model Training**

In [41]:
!pip install imbalanced-learn

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [42]:
!pip install xgboost

Defaulting to user installation because normal site-packages is not writeable


[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [43]:
np.random.seed(42)

In [44]:
from imblearn.over_sampling import SMOTE

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [46]:
x_train, x_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

In [47]:
smote = SMOTE(random_state=42)

In [48]:
x_train_balanced, y_train_balanced = smote.fit_resample(x_train, y_train)

In [49]:
y_train_balanced_df = pd.DataFrame({'target': y_train_balanced})
y_train_balanced_df.groupby('target').size()

target
0    19862
1    19862
dtype: int64

**Model Training**

***Logistic Regression***

In [50]:
logit = LogisticRegression()

In [51]:
logit.fit(x_train_balanced, y_train_balanced)

LogisticRegression()

In [52]:
import pickle

In [53]:
with open('logisticPDModel.pkl','wb') as file:
    pickle.dump(logit, file)

In [54]:
logit.score(x_train_balanced, y_train_balanced)

0.7842614036854295

In [55]:
logit_prediction = logit.predict(x_test)
logit_prediction

array([0, 1, 0, ..., 1, 0, 1], shape=(6335,))

In [56]:
print(classification_report(y_test, logit_prediction))

              precision    recall  f1-score   support

           0       0.92      0.78      0.84      4984
           1       0.48      0.75      0.59      1351

    accuracy                           0.77      6335
   macro avg       0.70      0.77      0.72      6335
weighted avg       0.83      0.77      0.79      6335



In [57]:
print(confusion_matrix(y_test, logit_prediction))

[[3889 1095]
 [ 334 1017]]


In [58]:
print(logit.coef_[0])

[-0.02595756  0.06094949 -0.02909438 -0.66288844  1.00151923  1.39874579
 -0.03676408 -0.78817973 -2.10085457  0.45937113 -1.28146439 -0.39455737
 -0.58626863 -1.02011741 -1.6414327   0.08334772]


In [59]:
features_imp_logit = pd.DataFrame({'features': x_train_balanced.columns, 'logit_imp': logit.coef_[0]})

***Random Forest***

In [60]:
rf = RandomForestClassifier()

In [61]:
rf.fit(x_train_balanced, y_train_balanced)

RandomForestClassifier()

In [62]:
with open('RandomForestPDModel.pkl','wb') as file:
    pickle.dump(rf, file)

In [63]:
rf.score(x_train_balanced, y_train_balanced)

1.0

In [64]:
rf_prediction = rf.predict(x_test)
rf_prediction

array([0, 0, 0, ..., 0, 0, 1], shape=(6335,))

In [65]:
print(classification_report(y_test, rf_prediction))

              precision    recall  f1-score   support

           0       0.92      0.97      0.94      4984
           1       0.85      0.71      0.77      1351

    accuracy                           0.91      6335
   macro avg       0.89      0.84      0.86      6335
weighted avg       0.91      0.91      0.91      6335



In [66]:
print(confusion_matrix(y_test, rf_prediction))

[[4812  172]
 [ 394  957]]


In [67]:
rf.feature_importances_

array([0.06046651, 0.14392431, 0.07527162, 0.08112071, 0.2084673 ,
       0.20636737, 0.05951228, 0.00036943, 0.02153749, 0.04895707,
       0.01544948, 0.01739267, 0.00924037, 0.01383707, 0.01823747,
       0.01984885])

In [68]:
features_imp_rf = pd.DataFrame({'features': x_train_balanced.columns, 'rf_imp': rf.feature_importances_})

**XgBoost Model**

In [69]:
xgb_model = XGBClassifier(tree_method = 'exact')

In [70]:
xgb_model.fit(x_train_balanced, y_train_balanced.values.ravel())

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [71]:
with open('XGBoostPDModel.pkl','wb') as file:
    pickle.dump(xgb_model, file)

In [72]:
xgb_model.score(x_train_balanced, y_train_balanced.ravel())

C:\Users\SHREYA PAI\AppData\Local\Temp\ipykernel_9576\211688295.py:1: FutureWarning: Series.ravel is deprecated. The underlying array is already 1D, so ravel is not necessary.  Use `to_numpy()` for conversion to a numpy array instead.
  xgb_model.score(x_train_balanced, y_train_balanced.ravel())


0.965914812204209

In [73]:
xgb_prediction = xgb_model.predict(x_test)
xgb_prediction

array([0, 0, 0, ..., 0, 0, 1], shape=(6335,))

In [74]:
print(classification_report(y_test, xgb_prediction))

              precision    recall  f1-score   support

           0       0.93      0.98      0.95      4984
           1       0.90      0.71      0.79      1351

    accuracy                           0.92      6335
   macro avg       0.91      0.84      0.87      6335
weighted avg       0.92      0.92      0.92      6335



In [75]:
print(confusion_matrix(y_test, xgb_prediction))

[[4880  104]
 [ 392  959]]


In [76]:
features_imp_xgb = pd.DataFrame({'features': x_train_balanced.columns, 'xgb_imp': xgb_model.feature_importances_})
features_imp_xgb.sort_values(by='xgb_imp', ascending=False)

,features,xgb_imp
8,OWN,0.190757
5,loan_percent_income,0.119928
9,RENT,0.110714
14,VENTURE,0.091653
6,cb_person_cred_hist_length,0.077309
4,loan_int_rate,0.072686
11,HOMEIMPROVEMENT,0.057206
10,EDUCATION,0.049369
2,person_emp_length,0.047232
13,PERSONAL,0.046267


In [77]:
feature_imp = pd.concat([features_imp_logit, features_imp_rf, features_imp_xgb], axis=1)
feature_imp

,features,logit_imp,features,rf_imp,features,xgb_imp
0,person_age,-0.025958,person_age,0.060467,person_age,0.040973
1,person_income,0.060949,person_income,0.143924,person_income,0.038819
2,person_emp_length,-0.029094,person_emp_length,0.075272,person_emp_length,0.047232
3,loan_amnt,-0.662888,loan_amnt,0.081121,loan_amnt,0.008449
4,loan_int_rate,1.001519,loan_int_rate,0.208467,loan_int_rate,0.072686
5,loan_percent_income,1.398746,loan_percent_income,0.206367,loan_percent_income,0.119928
6,cb_person_cred_hist_length,-0.036764,cb_person_cred_hist_length,0.059512,cb_person_cred_hist_length,0.077309
7,OTHER,-0.788180,OTHER,0.000369,OTHER,0.006625
8,OWN,-2.100855,OWN,0.021537,OWN,0.190757
9,RENT,0.459371,RENT,0.048957,RENT,0.110714


**Further Exploration**

In [97]:
xgb_prediction_df = pd.DataFrame({'test_indices_xgb': x_test.index, 'xgb_pred': xgb_prediction})
logit_prediction_df = pd.DataFrame({'test_indices_logit': x_test.index, 'logit_pred': logit_prediction})
rf_prediction_df = pd.DataFrame({'test_indices_rf': x_test.index, 'rf_pred': rf_prediction})

In [98]:
logit_df = logit_prediction_df.drop(['test_indices_logit'], axis=1)
rf_df = rf_prediction_df.drop(['test_indices_rf'], axis=1)
xgb_df = xgb_prediction_df.drop(['test_indices_xgb'], axis=1)

In [115]:
final_pred_with_NA = pd.concat([cr_data_copy, logit_df, rf_df, xgb_df], axis=1)

In [116]:
final_pred_with_NA.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,logit_pred,rf_pred,xgb_pred
0,21,9600,OWN,5.0,EDUCATION,1000,11.14,0,0.10,N,2,0.0,0.0,0.0
1,25,9600,MORTGAGE,1.0,MEDICAL,5500,12.87,1,0.57,N,3,1.0,0.0,0.0
2,23,65500,RENT,4.0,MEDICAL,35000,15.23,1,0.53,N,2,0.0,0.0,0.0
3,24,54400,RENT,8.0,MEDICAL,35000,14.27,1,0.55,Y,4,1.0,1.0,1.0
4,21,9900,OWN,2.0,VENTURE,2500,7.14,1,0.25,N,2,0.0,0.0,0.0


In [119]:
final_pred_with_NA.shape

(31671, 14)

In [120]:
final_pred_with_NA.to_excel(r"C:\Users\SHREYA PAI\Files\pd_prediction_with_NA.xlsx", index=False)

In [121]:
final_pred_with_NA.dropna(inplace=True)

In [122]:
final_pred_with_NA.shape

(6335, 14)

In [124]:
final_pred_with_NA.to_excel(r"C:\Users\SHREYA PAI\Files\pd_prediction_without_NA.xlsx", index=False)

In [125]:
predictions_df=pd.DataFrame(y_test)

In [126]:
predictions = pd.concat([predictions_df.reset_index(drop=True), logit_df, rf_df, xgb_df], axis=1)
predictions.columns=["Actual_status", "Logistic_regression", "Random_forest", "XGBoost"]

In [127]:
predictions

,Actual_status,Logistic_regression,Random_forest,XGBoost
0,0,0,0,0
1,0,1,0,0
2,0,0,0,0
3,1,1,1,1
4,0,0,0,0
...,...,...,...,...
6330,1,1,1,1
6331,0,0,0,0
6332,0,1,0,0
6333,0,0,0,0


In [128]:
predictions.to_excel(r"C:\Users\SHREYA PAI\Files\test_data_plus_prediction.xlsx", index=False)